@HostAddressRoot = https://localhost:7293

GET {{HostAddressRoot}}/api/destinations
Accept: application/json

###

GET {{HostAddressRoot}}/api/itineraries?searchFor=Paris
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1haG1tIiwic3ViIjoibWFobW0iLCJqdGkiOiJkZjkwNTZkZiIsImZlYXR1cmUiOiJnZXQtaXRpbmVyYXJpZXMiLCJhdWQiOiJ0cmF2ZWxpbnNwaXJhdGlvbi1hcGkiLCJuYmYiOjE3MjUwMDMzNjUsImV4cCI6MTczMjk1MjE2NSwiaWF0IjoxNzI1MDAzMzY2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.cJr158Lqf3NB4RDPkemGowMNWqbglk0I2gQ5_WfdL_E

###

GET {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json

###

GET {{HostAddressRoot}}/api/itineraries/1111/stops
Accept: application/json

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1haG1tIiwic3ViIjoibWFobW0iLCJqdGkiOiI4YTAwNWFhYiIsInNjb3BlIjoid3JpdGUiLCJhdWQiOiJ0cmF2ZWxpbnNwaXJhdGlvbi1hcGkiLCJuYmYiOjE3MjUwMDM2ODQsImV4cCI6MTczMjk1MjQ4NCwiaWF0IjoxNzI1MDAzNjg1LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.gBmnVLTc6sO-FzgtHhTT04wkW1p_81LD5gG6JFHD-5E

{
  "name":"A stop for testing",
  "imageUri":"https://localhost:7120/images/stopfortesting"
}

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json

{
  "imageUri":"https://localhost:7120/images/stopfortesting"
}

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json

{
  "imageUri":"thisinvaliduri"
}

###

PUT {{HostAddressRoot}}/api/itineraries/1/stops/1
Accept: application/json
Content-Type: application/json

{
  "name": "An updated name"
}

###

GET {{HostAddressRoot}}/api/itineraries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1haG1tIiwic3ViIjoibWFobW0iLCJqdGkiOiI0OTVmNzE1MiIsImF1ZCI6InRyYXZlbGluc3BpcmF0aW9uLWFwaSIsIm5iZiI6MTcyNDk1NTIyOCwiZXhwIjoxNzMyOTA0MDI4LCJpYXQiOjE3MjQ5NTUyMjgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.Y12fFmPLq3AF6PBt0xVR6q34rK9PmQXJWVaAxgZFPPQ

###